# ===================================================================
# NETCANDRUG PROJECT - SCRIPT 07: PATHWAY ENRICHMENT ANALYSIS
# ===================================================================
#
# OBJECTIVE:
# 1. Identify which biological pathways are enriched with DEGs.
#
# APPROACH:
# - This script uses a pre-built and reliable translation map
#   ('uniprot_to_genesymbol.csv'), generated by script 06.
#
# ===================================================================

import pandas as pd
from scipy.stats import hypergeom
from statsmodels.stats.multitest import multipletests
from tqdm import tqdm
import os
import sys

# Add parent directory to path to import config
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config

print("=" * 80)
print("SCRIPT 07: PATHWAY ENRICHMENT ANALYSIS")
print("=" * 80)

# --- 1. Configuration ---
deg_file = config.DEG_FILE
pathway_map_file = config.PATHWAY_MAP_FILE
id_map_file = config.ID_MAP_FILE
output_file = config.PATHWAYS_FILE
FDR_THRESHOLD = config.PATHWAY_FDR_THRESHOLD

# --- 2. Load and Process Base Data ---
print("\n--- STEP 1: Loading and processing base data ---")

degs_df = pd.read_csv(deg_file)
deg_set = set(degs_df['gene_name'].dropna())
print(f"  - Loaded {len(deg_set)} DEGs.")

pathway_map_df = pd.read_csv(pathway_map_file)
print(f"  - Loaded raw pathway map with {pathway_map_df.shape[0]} rows.")

# Load our new translation dictionary
if not os.path.exists(id_map_file):
    print(f"❌ ERROR: Translation file '{id_map_file}' not found.")
    print("   Please run the R script '06_create_id_map.R' first.")
    exit()
id_map_df = pd.read_csv(id_map_file)
uniprot_to_gene = pd.Series(id_map_df.gene_symbol.values, index=id_map_df.uniprot_id).to_dict()
print(f"  - Loaded translation dictionary with {len(uniprot_to_gene)} entries.")

# Add 'gene_symbol' column to pathway map
pathway_map_df['gene_symbol'] = pathway_map_df['uniprot_id'].map(uniprot_to_gene)
pathway_map_df.dropna(subset=['gene_symbol'], inplace=True)
print(f"  - Pathway map translated. {pathway_map_df.shape[0]} rows remaining.")

# --- 3. Prepare and Execute Analysis ---
print("\n--- STEP 2: Executing enrichment analysis ---")

universe_genes = set(pathway_map_df['gene_symbol'].dropna())
M = len(universe_genes)
K = len(deg_set.intersection(universe_genes))
print(f"  - Universe (M): {M} genes. DEGs in universe (K): {K} genes.")

pathway_to_genes = pathway_map_df.groupby('pathway_name')['gene_symbol'].apply(set)

results = []
for pathway_name, genes in tqdm(pathway_to_genes.items(), desc="Analyzing pathways"):
    n = len(genes)
    k = len(genes.intersection(deg_set))
    p_value = hypergeom.sf(k - 1, M, K, n)
    results.append({
        'pathway_name': pathway_name, 'p_value': p_value, 'degs_in_pathway': k,
        'genes_in_pathway': n, 'degs_in_pathway_list': sorted(list(genes.intersection(deg_set)))
    })

results_df = pd.DataFrame(results)

# --- 4. Correct, Filter and Save ---
print("\n--- STEP 3: Correcting p-values and saving results ---")
if not results_df.empty:
    _, corrected_p_values, _, _ = multipletests(results_df['p_value'], alpha=FDR_THRESHOLD, method='fdr_bh')
    results_df['FDR'] = corrected_p_values
    dysregulated_pathways = results_df[results_df['FDR'] < FDR_THRESHOLD].copy()
    dysregulated_pathways = dysregulated_pathways.sort_values('FDR')
    dysregulated_pathways['degs_in_pathway_list'] = dysregulated_pathways['degs_in_pathway_list'].apply(lambda x: ','.join(x))
else:
    dysregulated_pathways = pd.DataFrame()

print(f"  - Found {len(dysregulated_pathways)} significantly dysregulated pathways.")

# Ensure output directory exists
os.makedirs(os.path.dirname(output_file), exist_ok=True)

dysregulated_pathways.to_csv(output_file, index=False)
print(f"  ✅ List of dysregulated pathways saved at: {output_file}")

# --- 5. Final Report ---
print("\n" + "=" * 80)
print("PATHWAY ANALYSIS REPORT")
print("=" * 80)
if not dysregulated_pathways.empty:
    print(f"\n🔝 Top 15 Most Dysregulated Pathways:")
    print(dysregulated_pathways.head(15)[['pathway_name', 'FDR', 'degs_in_pathway', 'genes_in_pathway']].to_string(index=False))
else:
    print("\nNo significantly dysregulated pathways were found.")

print("\n" + "=" * 80)
print("SCRIPT 07 COMPLETED!")
print("=" * 80)
